pipeline {
    agent any
    tools {
        maven 'Maven3'
    }

    environment {
        PATH = "C:\\Program Files\\Docker\\Docker\\resources\\bin;${env.PATH}"
        JAVA_HOME = 'C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.15.6-hotspot'  // Adjust to your actual JDK pat
        SONARQUBE_SERVER = 'SonarQubeServer1'  // The name of the SonarQube server configured in Jenkins
        SONAR_TOKEN = 'squ_54b7095425c7a9f0f0cd177e0785bb0470868b93' // Store the token securely
        DOCKERHUB_CREDENTIALS_ID = '73a53345-c223-4cfc-aa23-0a92815a7a22'
        DOCKERHUB_REPO = 'vernere/SonarQubeJenkins'
        DOCKER_IMAGE_TAG = 'latest'


    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/vernere/SonarJenkins.git'
            }
        }

        stage('Build') {
            steps {
                dir('sep2_week5_inclass_s2') {
                    bat 'mvn clean install'
                }
            }
        }

        stage('SonarQube Analysis') {
                    steps {
                        dir('sep2_week5_inclass_s2') {
                            withSonarQubeEnv('SonarQubeServer1') {
                                bat """
                                    mvn sonar:sonar ^
                                    -Dsonar.projectKey=devops-demo ^
                                    -Dsonar.projectName=DevOps-Demo ^
                                    -Dsonar.host.url=http://localhost:9000 ^
                                    -Dsonar.login=${env.SONAR_TOKEN}
                                """
                            }
                        }
                    }
                }



        stage('Build Docker Image') {
                    steps {
                        dir('sep2_week5_inclass_s2') {
                            script {
                                docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}")
                                // Or specify Dockerfile path explicitly if needed
                                // docker.build("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}", "-f ./Dockerfile .")
                            }
                        }
                    }
                }

                stage('Push Docker Image to Docker Hub') {
                    steps {
                        script {
                            docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS_ID) {
                                docker.image("${DOCKERHUB_REPO}:${DOCKER_IMAGE_TAG}").push()
                            }
                        }
                    }
                }
    }
}
